homeassistant:
  # Name of the location where Home Assistant is running
  name: Main 
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include config/customize.yaml

group: !include config/groups.yaml
automation: !include config/automation.yaml
zwave: !include config/zwave.yaml
sensor: !include config/sensor.yaml

# Enables the frontend
frontend:

http:
  api_password: !secret http_password 

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

device_tracker:
  - platform: nmap_tracker
    consider_home: 1800
    hosts:
      - 192.168.1.15
