media_player.cass_family:
  hidden: true
light.linear_lb60z1_dimmable_led_light_bulb_level_2_0:
  friendly_name: Living room overhead 1
light.linear_lb60z1_dimmable_led_light_bulb_level_3_0:
  friendly_name: Living room overhead 2
light.ge_12724_3way_dimmer_switch_level_4_0:
  friendly_name: Kitchen recessed lights
light.linear_lb60z1_dimmable_led_light_bulb_level_5_0:
  friendly_name: Bedroom overhead 1
light.linear_lb60z1_dimmable_led_light_bulb_level_6_0:
  friendly_name: Bedroom overhead 2
climate.living_room:
  icon: mdi:thermometer
